# Generated by Django 5.2.8 on 2025-12-05 06:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0003_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlog',
            name='applicant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='crm_app.applicant'),
        ),
    ]
