# Generated by Django 5.2.8 on 2025-12-05 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0005_applicant_address_applicant_preferred_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='followup',
            name='channel',
            field=models.CharField(choices=[('email', 'Email'), ('sms', 'SMS'), ('phone', 'Phone'), ('in_app', 'In App'), ('other', 'Other')], default='email', max_length=32),
        ),
    ]
