# Generated by Django 5.2.8 on 2025-12-05 12:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0007_academicrecord_end_year_academicrecord_start_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='followup',
            name='call_record',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='followups', to='crm_app.callrecord'),
        ),
        migrations.AddField(
            model_name='followup',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('scheduled', 'Scheduled'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=32),
        ),
        migrations.AlterField(
            model_name='followup',
            name='channel',
            field=models.CharField(choices=[('email', 'Email'), ('sms', 'SMS'), ('phone', 'Phone'), ('ai_call', 'AI Call'), ('in_app', 'In App'), ('other', 'Other')], default='email', max_length=32),
        ),
    ]
