# Generated by Django 5.2.8 on 2025-12-11 05:23

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0008_add_ai_call_scheduling'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdIntegration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('google_ads', 'Google Ads'), ('meta_ads', 'Meta Ads')], max_length=32)),
                ('account_id', models.CharField(blank=True, help_text='Platform Account/Customer ID', max_length=128, null=True)),
                ('account_name', models.CharField(blank=True, max_length=255, null=True)),
                ('access_token', models.TextField(blank=True, help_text='OAuth access token (encrypted in production)', null=True)),
                ('refresh_token', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('connected', 'Connected'), ('disconnected', 'Disconnected'), ('error', 'Error')], default='disconnected', max_length=32)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ad_integrations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ad Integration',
                'verbose_name_plural': 'Ad Integrations',
                'ordering': ('-created_at',),
                'unique_together': {('user', 'platform', 'account_id')},
            },
        ),
        migrations.CreateModel(
            name='AdCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_campaign_id', models.CharField(help_text='Campaign ID from the platform', max_length=128)),
                ('name', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('active', 'Active'), ('paused', 'Paused'), ('ended', 'Ended'), ('draft', 'Draft')], default='active', max_length=32)),
                ('objective', models.CharField(blank=True, help_text='e.g., Conversions, Traffic, Awareness', max_length=128, null=True)),
                ('daily_budget', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('lifetime_budget', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('total_spend', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('currency', models.CharField(default='USD', max_length=8)),
                ('impressions', models.BigIntegerField(default=0)),
                ('clicks', models.BigIntegerField(default=0)),
                ('conversions', models.IntegerField(default=0)),
                ('ctr', models.DecimalField(decimal_places=4, default=0, help_text='Click-through rate', max_digits=6)),
                ('cpc', models.DecimalField(decimal_places=2, default=0, help_text='Cost per click', max_digits=10)),
                ('cpm', models.DecimalField(decimal_places=2, default=0, help_text='Cost per 1000 impressions', max_digits=10)),
                ('cost_per_conversion', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('raw_data', models.JSONField(blank=True, null=True)),
                ('last_synced_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('integration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaigns', to='crm_app.adintegration')),
            ],
            options={
                'verbose_name': 'Ad Campaign',
                'verbose_name_plural': 'Ad Campaigns',
                'ordering': ('-total_spend',),
                'unique_together': {('integration', 'external_campaign_id')},
            },
        ),
    ]
