# Generated by Django 5.2.8 on 2026-01-10 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0011_add_tenant_to_data_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenantsettings',
            name='elevenlabs_agent_id',
            field=models.CharField(blank=True, help_text='Agent ID for ElevenLabs', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='tenantsettings',
            name='elevenlabs_api_key',
            field=models.CharField(blank=True, help_text='API Key for ElevenLabs', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='tenantsettings',
            name='elevenlabs_config',
            field=models.JSONField(blank=True, default=dict, help_text='Additional ElevenLabs config'),
        ),
        migrations.AddField(
            model_name='tenantsettings',
            name='smartflo_api_key',
            field=models.CharField(blank=True, help_text='API Key for Smartflo Integration', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='tenantsettings',
            name='smartflo_caller_id',
            field=models.CharField(blank=True, help_text='Smartflo DID/Caller ID', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='tenantsettings',
            name='smartflo_config',
            field=models.JSONField(blank=True, default=dict, help_text='Additional Smartflo config'),
        ),
        migrations.AddField(
            model_name='tenantsettings',
            name='smartflo_voicebot_api_key',
            field=models.CharField(blank=True, help_text='Voice Bot API Key (if different)', max_length=255, null=True),
        ),
    ]
