# Generated by Django 6.0 on 2026-01-16 10:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0013_enhance_lead_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='followup',
            name='crm_lead',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='followups', to='crm_app.lead'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('qualified', 'Qualified'), ('converted', 'Converted'), ('junk', 'Junk'), ('lost', 'Lost')], default='new', max_length=32),
        ),
        migrations.CreateModel(
            name='TenantUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField()),
                ('month', models.PositiveIntegerField()),
                ('smartflo_calls_made', models.PositiveIntegerField(default=0, help_text='Total outbound calls initiated')),
                ('smartflo_calls_answered', models.PositiveIntegerField(default=0, help_text='Calls that were answered')),
                ('smartflo_call_minutes', models.DecimalField(decimal_places=2, default=0, help_text='Total call duration in minutes', max_digits=10)),
                ('ai_api_calls', models.PositiveIntegerField(default=0, help_text='Total AI API calls')),
                ('ai_tokens_used', models.PositiveIntegerField(default=0, help_text='Total AI tokens consumed')),
                ('leads_created', models.PositiveIntegerField(default=0)),
                ('emails_sent', models.PositiveIntegerField(default=0)),
                ('sms_sent', models.PositiveIntegerField(default=0)),
                ('whatsapp_messages_sent', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_records', to='crm_app.tenant')),
            ],
            options={
                'verbose_name': 'Tenant Usage',
                'verbose_name_plural': 'Tenant Usage Records',
                'ordering': ['-year', '-month'],
                'unique_together': {('tenant', 'year', 'month')},
            },
        ),
    ]
