# Generated by Django 6.0 on 2026-01-17 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0014_followup_crm_lead_alter_lead_status_tenantusage'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='intake',
            field=models.CharField(blank=True, help_text='e.g., Fall 2025, Spring 2026', max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='priority',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=16),
        ),
        migrations.AddField(
            model_name='application',
            name='stage',
            field=models.CharField(choices=[('inquiry', 'Inquiry'), ('documents_pending', 'Documents Pending'), ('application_submitted', 'Application Submitted'), ('offer_received', 'Offer Received'), ('fee_paid', 'Fee Paid'), ('i20_cas_received', 'I-20/CAS Received'), ('visa_applied', 'Visa Applied'), ('visa_interview', 'Visa Interview'), ('visa_approved', 'Visa Approved'), ('pre_departure', 'Pre-Departure'), ('enrolled', 'Enrolled'), ('rejected', 'Rejected'), ('withdrawn', 'Withdrawn')], default='inquiry', max_length=32),
        ),
        migrations.AddField(
            model_name='application',
            name='university_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='visa_interview_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
