# Generated by Django 6.0 on 2026-01-21 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0016_whatsapp_message_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='enquiry_type',
            field=models.CharField(blank=True, help_text='Type of enquiry: study_visa, visitor_visa, spouse_visa, work_visa, other', max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='exam_type',
            field=models.CharField(blank=True, help_text='English exam type: IELTS, PTE, Other, Not Taken', max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='qualification_gap',
            field=models.CharField(blank=True, help_text="Gap in education/work (e.g., '2 years after 12th')", max_length=255, null=True),
        ),
    ]
