# Generated by Django 6.0 on 2026-01-28 09:30

import crm_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0017_lead_enquiry_type_lead_exam_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenantsettings',
            name='favicon',
            field=models.ImageField(blank=True, help_text='Tenant favicon (ICO/PNG, 32x32 or 64x64)', null=True, upload_to=crm_app.models.tenant_favicon_upload_path),
        ),
        migrations.AddField(
            model_name='tenantsettings',
            name='font_family',
            field=models.CharField(default='Inter, system-ui, sans-serif', help_text="Font family for the tenant's branding", max_length=100),
        ),
        migrations.AddField(
            model_name='tenantsettings',
            name='logo',
            field=models.ImageField(blank=True, help_text='Tenant logo (PNG/SVG recommended, transparent background)', null=True, upload_to=crm_app.models.tenant_logo_upload_path),
        ),
        migrations.AlterField(
            model_name='tenantsettings',
            name='favicon_url',
            field=models.URLField(blank=True, help_text='External URL to favicon (if not using upload)', null=True),
        ),
        migrations.AlterField(
            model_name='tenantsettings',
            name='logo_url',
            field=models.URLField(blank=True, help_text='External URL to logo (if not using upload)', null=True),
        ),
    ]
