# Generated by Django 6.0 on 2026-01-28 09:56

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0018_tenantsettings_favicon_tenantsettings_font_family_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsageAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('quota_warning', 'Quota Warning (80%)'), ('quota_exceeded', 'Quota Exceeded'), ('cost_warning', 'Cost Warning'), ('rate_limit', 'Rate Limit Hit')], max_length=50)),
                ('service', models.CharField(blank=True, max_length=50)),
                ('message', models.TextField()),
                ('current_value', models.DecimalField(decimal_places=2, max_digits=15)),
                ('threshold_value', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('acknowledged', 'Acknowledged'), ('resolved', 'Resolved')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_alerts', to='crm_app.tenant')),
            ],
            options={
                'verbose_name': 'Usage Alert',
                'verbose_name_plural': 'Usage Alerts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UsageQuota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('openai_token_limit', models.BigIntegerField(blank=True, help_text='Max tokens per month', null=True)),
                ('elevenlabs_character_limit', models.BigIntegerField(blank=True, help_text='Max characters per month', null=True)),
                ('smartflo_minute_limit', models.DecimalField(blank=True, decimal_places=2, help_text='Max minutes per month', max_digits=10, null=True)),
                ('monthly_cost_limit', models.DecimalField(blank=True, decimal_places=2, help_text='Max USD per month', max_digits=10, null=True)),
                ('openai_rpm', models.IntegerField(blank=True, help_text='Requests per minute', null=True)),
                ('elevenlabs_rpm', models.IntegerField(blank=True, null=True)),
                ('smartflo_rpm', models.IntegerField(blank=True, null=True)),
                ('alert_at_percentage', models.IntegerField(default=80, help_text='Send alert when reaching X% of quota')),
                ('alert_email', models.EmailField(blank=True, help_text='Email for quota alerts', max_length=254, null=True)),
                ('is_suspended', models.BooleanField(default=False, help_text='Suspend API access if quota exceeded')),
                ('suspension_reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='usage_quota', to='crm_app.tenant')),
            ],
            options={
                'verbose_name': 'Usage Quota',
                'verbose_name_plural': 'Usage Quotas',
            },
        ),
        migrations.CreateModel(
            name='APIUsageLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(choices=[('openai', 'OpenAI'), ('elevenlabs', 'ElevenLabs'), ('smartflo', 'Smartflo'), ('custom', 'Custom API')], max_length=50)),
                ('endpoint', models.CharField(help_text='API endpoint called (e.g., /v1/chat/completions)', max_length=255)),
                ('request_timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('request_method', models.CharField(default='POST', max_length=10)),
                ('request_params', models.JSONField(blank=True, default=dict, help_text='Request parameters (sanitized)')),
                ('response_timestamp', models.DateTimeField(blank=True, null=True)),
                ('response_status', models.IntegerField(blank=True, help_text='HTTP status code', null=True)),
                ('response_time_ms', models.IntegerField(blank=True, help_text='Response time in milliseconds', null=True)),
                ('tokens_used', models.IntegerField(blank=True, help_text='Tokens (OpenAI)', null=True)),
                ('characters_used', models.IntegerField(blank=True, help_text='Characters (ElevenLabs)', null=True)),
                ('duration_seconds', models.DecimalField(blank=True, decimal_places=2, help_text='Duration (Voice calls)', max_digits=10, null=True)),
                ('credits_used', models.DecimalField(blank=True, decimal_places=4, help_text='Credits consumed', max_digits=10, null=True)),
                ('estimated_cost', models.DecimalField(blank=True, decimal_places=4, help_text='Cost in USD', max_digits=10, null=True)),
                ('error', models.TextField(blank=True, help_text='Error message if request failed', null=True)),
                ('user_id', models.CharField(blank=True, help_text='User who initiated the request', max_length=255, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_usage_logs', to='crm_app.tenant')),
            ],
            options={
                'verbose_name': 'API Usage Log',
                'verbose_name_plural': 'API Usage Logs',
                'ordering': ['-request_timestamp'],
                'indexes': [models.Index(fields=['tenant', 'service', '-request_timestamp'], name='crm_app_api_tenant__c2dae3_idx'), models.Index(fields=['tenant', '-request_timestamp'], name='crm_app_api_tenant__9a7e59_idx'), models.Index(fields=['service', '-request_timestamp'], name='crm_app_api_service_9fb15d_idx')],
            },
        ),
        migrations.CreateModel(
            name='TenantUsageSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_start', models.DateField(help_text='Start of billing period (usually 1st of month)')),
                ('period_end', models.DateField(help_text='End of billing period')),
                ('openai_requests', models.IntegerField(default=0)),
                ('openai_tokens', models.BigIntegerField(default=0)),
                ('openai_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('elevenlabs_requests', models.IntegerField(default=0)),
                ('elevenlabs_characters', models.BigIntegerField(default=0)),
                ('elevenlabs_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('smartflo_calls', models.IntegerField(default=0)),
                ('smartflo_duration_minutes', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('smartflo_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('custom_requests', models.IntegerField(default=0)),
                ('custom_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('total_requests', models.IntegerField(default=0)),
                ('total_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_summaries', to='crm_app.tenant')),
            ],
            options={
                'verbose_name': 'Tenant Usage Summary',
                'verbose_name_plural': 'Tenant Usage Summaries',
                'ordering': ['-period_start', 'tenant'],
                'indexes': [models.Index(fields=['tenant', '-period_start'], name='crm_app_ten_tenant__1e8993_idx'), models.Index(fields=['-period_start'], name='crm_app_ten_period__36fa1f_idx')],
                'unique_together': {('tenant', 'period_start')},
            },
        ),
    ]
