# Generated by Django 6.0 on 2026-01-28 11:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0019_usagealert_usagequota_apiusagelog_tenantusagesummary'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lead',
            name='address',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='dob',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='passport_number',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='preferred_country',
        ),
        migrations.AddField(
            model_name='lead',
            name='is_manual_only',
            field=models.BooleanField(default=False, help_text='If True, disables all AI automation for this lead (used for walk-ins)'),
        ),
        migrations.AddField(
            model_name='lead',
            name='receptionist',
            field=models.ForeignKey(blank=True, help_text='Staff member who received this walk-in lead', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_walkin_leads', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='lead',
            name='walked_in_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when the lead physically walked into the office', null=True),
        ),
        migrations.AlterField(
            model_name='lead',
            name='source',
            field=models.CharField(blank=True, choices=[('website', 'Website'), ('referral', 'Referral'), ('walk-in', 'Walk-in'), ('phone', 'Phone'), ('email', 'Email'), ('social_media', 'Social Media'), ('advertisement', 'Advertisement'), ('other', 'Other')], help_text='Source of the lead', max_length=128, null=True),
        ),
    ]
