# Generated by Manual Fix on 2026-01-28

from django.db import migrations, models
import django.db.models.deletion
from django.conf import settings


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0020_remove_lead_address_remove_lead_dob_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # Add is_manual_only field if it doesn't exist
        migrations.RunSQL(
            sql="""
                ALTER TABLE crm_app_lead ADD COLUMN is_manual_only INTEGER NOT NULL DEFAULT 0;
            """,
            reverse_sql="""
                ALTER TABLE crm_app_lead DROP COLUMN is_manual_only;
            """,
            state_operations=[
                migrations.AddField(
                    model_name='lead',
                    name='is_manual_only',
                    field=models.BooleanField(default=False, help_text='If True, disables all AI automation for this lead (used for walk-ins)'),
                ),
            ]
        ),
        # Add walked_in_at field if it doesn't exist
        migrations.RunSQL(
            sql="""
                ALTER TABLE crm_app_lead ADD COLUMN walked_in_at TEXT NULL;
            """,
            reverse_sql="""
                ALTER TABLE crm_app_lead DROP COLUMN walked_in_at;
            """,
            state_operations=[
                migrations.AddField(
                    model_name='lead',
                    name='walked_in_at',
                    field=models.DateTimeField(blank=True, help_text='Timestamp when this lead walked into the office', null=True),
                ),
            ]
        ),
        # Add receptionist field if it doesn't exist  
        migrations.RunSQL(
            sql="""
                ALTER TABLE crm_app_lead ADD COLUMN receptionist_id INTEGER NULL 
                REFERENCES auth_user(id) ON DELETE SET NULL;
            """,
            reverse_sql="""
                ALTER TABLE crm_app_lead DROP COLUMN receptionist_id;
            """,
            state_operations=[
                migrations.AddField(
                    model_name='lead',
                    name='receptionist',
                    field=models.ForeignKey(blank=True, help_text='Staff member who received this walk-in lead', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_walkin_leads', to=settings.AUTH_USER_MODEL),
                ),
            ]
        ),
    ]
