# Generated by Django 6.0 on 2026-01-29 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0021_add_missing_lead_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='walked_in_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when the lead physically walked into the office', null=True),
        ),
    ]
