# Generated by Django 6.0 on 2026-01-29 12:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0022_alter_lead_walked_in_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='source',
            field=models.CharField(blank=True, choices=[('website', 'Website'), ('facebook', 'Facebook Lead Ad'), ('google', 'Google Ads'), ('meta_ads', 'Meta Ads'), ('walk-in', 'Walk-in'), ('referral', 'Referral'), ('phone', 'Phone Inquiry'), ('email', 'Email'), ('whatsapp', 'WhatsApp'), ('social_media', 'Social Media'), ('advertisement', 'Advertisement'), ('other', 'Other')], help_text='Source of the lead', max_length=128, null=True),
        ),
        migrations.CreateModel(
            name='CounselorTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_enrollments', models.IntegerField(help_text='Number of enrollments required to complete this target')),
                ('completed_enrollments', models.IntegerField(default=0, help_text='Number of enrollments achieved so far')),
                ('period_type', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('yearly', 'Yearly')], default='monthly', max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('overdue', 'Overdue'), ('cancelled', 'Cancelled')], default='active', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='targets_assigned', to=settings.AUTH_USER_MODEL)),
                ('counselor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='targets', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='counselor_targets', to='crm_app.tenant')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['counselor', 'status'], name='crm_app_cou_counsel_07af24_idx'), models.Index(fields=['start_date', 'end_date'], name='crm_app_cou_start_d_a1e0a1_idx')],
            },
        ),
    ]
