# Generated by Django 6.0 on 2026-01-30 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0023_alter_lead_source_counselortarget'),
    ]

    operations = [
        migrations.AddField(
            model_name='counselortarget',
            name='target_applications',
            field=models.IntegerField(default=0, help_text='Target number of applications to generate'),
        ),
        migrations.AddField(
            model_name='counselortarget',
            name='target_calls',
            field=models.IntegerField(default=0, help_text='Target number of calls to make'),
        ),
        migrations.AddField(
            model_name='counselortarget',
            name='target_leads',
            field=models.IntegerField(default=0, help_text='Target number of new leads assigned'),
        ),
    ]
