# Generated by Django 5.2.8 on 2025-12-13 08:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
        ('crm_app', '0010_add_tenant_models'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='feature_flags',
            field=models.JSONField(blank=True, default=dict, help_text="Features unlocked by this product: {'crm': true, 'ielts_module': true, 'application_portal': true}"),
        ),
        migrations.AddField(
            model_name='subscription',
            name='billing_contact',
            field=models.ForeignKey(blank=True, help_text='Primary contact for billing communications', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='billing_subscriptions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='subscription',
            name='tenant',
            field=models.ForeignKey(blank=True, help_text='The tenant/organization this subscription belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='crm_app.tenant'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to=settings.AUTH_USER_MODEL),
        ),
    ]
