# Generated by Django 6.0 on 2026-01-24 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_add_tenant_subscription_and_product_features'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentlog',
            name='gateway',
            field=models.CharField(choices=[('stripe', 'Stripe'), ('razorpay', 'Razorpay'), ('manual', 'Manual'), ('bank_transfer', 'Bank Transfer')], max_length=20),
        ),
    ]
