# Generated by Django 5.2.8 on 2025-12-12 12:01

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IELTSTest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('test_type', models.CharField(choices=[('academic', 'Academic'), ('general', 'General Training')], default='academic', max_length=20)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='QuestionGroup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('instructions', models.TextField(blank=True)),
                ('content', models.TextField(blank=True, help_text='Reading passage text or transcript')),
                ('media_file', models.FileField(blank=True, help_text='Audio for listening or Image for reading', null=True, upload_to='ielts/media/')),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('question_text', models.TextField()),
                ('question_type', models.CharField(choices=[('multiple_choice', 'Multiple Choice'), ('text_input', 'Text Input (Gap Fill)'), ('true_false', 'True/False/Not Given'), ('matching', 'Matching'), ('essay', 'Essay (Writing)'), ('speech', 'Speech Recording (Speaking)')], max_length=20)),
                ('options', models.JSONField(blank=True, default=list, help_text='List of options for MCQs')),
                ('correct_answer', models.TextField(blank=True, help_text='Correct answer string or JSON')),
                ('order', models.PositiveIntegerField(default=0)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='ielts_service.questiongroup')),
            ],
        ),
        migrations.CreateModel(
            name='TestModule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('module_type', models.CharField(choices=[('listening', 'Listening'), ('reading', 'Reading'), ('writing', 'Writing'), ('speaking', 'Speaking')], max_length=20)),
                ('duration_minutes', models.PositiveIntegerField(default=60)),
                ('order', models.PositiveIntegerField(default=0)),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='ielts_service.ieltstest')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('test', 'module_type')},
            },
        ),
        migrations.AddField(
            model_name='questiongroup',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_groups', to='ielts_service.testmodule'),
        ),
        migrations.CreateModel(
            name='UserModuleAttempt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('band_score', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('raw_score', models.PositiveIntegerField(blank=True, null=True)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ielts_service.testmodule')),
            ],
        ),
        migrations.CreateModel(
            name='UserAnswer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('answer_text', models.TextField(blank=True)),
                ('audio_file', models.FileField(blank=True, help_text='For Speaking tasks', null=True, upload_to='ielts/responses/')),
                ('is_correct', models.BooleanField(blank=True, null=True)),
                ('marks_awarded', models.PositiveIntegerField(default=0)),
                ('feedback', models.TextField(blank=True, help_text='AI or Tutor feedback')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ielts_service.question')),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='ielts_service.usermoduleattempt')),
            ],
        ),
        migrations.CreateModel(
            name='UserTestSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('overall_band_score', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ielts_service.ieltstest')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ielts_attempts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='usermoduleattempt',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='module_attempts', to='ielts_service.usertestsession'),
        ),
    ]
