# Generated by Django 6.0 on 2026-01-15 09:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ielts_service', '0002_add_audio_start_time'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='usermoduleattempt',
            name='data',
            field=models.JSONField(blank=True, default=dict, help_text='Detailed results/feedback JSON'),
        ),
        migrations.CreateModel(
            name='IELTSUserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purpose', models.CharField(blank=True, choices=[('study_abroad', 'Study abroad'), ('immigration', 'Immigration'), ('work_abroad', 'Work abroad'), ('local_university', 'Study at local university'), ('other', 'Other'), ('teacher', 'IELTS teacher')], max_length=50)),
                ('test_type', models.CharField(blank=True, choices=[('general', 'General Training'), ('academic', 'Academic')], max_length=20)),
                ('attempt_type', models.CharField(blank=True, choices=[('first', 'First time'), ('writing', 'Writing retake'), ('speaking', 'Speaking retake'), ('listening', 'Listening retake'), ('reading', 'Reading retake'), ('full', 'Full test retake')], max_length=20)),
                ('target_score', models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True)),
                ('exam_date', models.CharField(blank=True, help_text="Date string YYYY-MM-DD or 'unknown'", max_length=20)),
                ('referral_source', models.CharField(blank=True, max_length=50)),
                ('onboarding_completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ielts_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'IELTS User Profile',
                'verbose_name_plural': 'IELTS User Profiles',
            },
        ),
    ]
