# Generated by Django 6.0 on 2026-01-23 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ielts_service', '0004_supportticket_ticketreply'),
    ]

    operations = [
        migrations.AddField(
            model_name='questiongroup',
            name='container',
            field=models.JSONField(blank=True, help_text='Structure for table completion, flow charts etc.', null=True),
        ),
    ]
