# Generated by Django 6.0 on 2026-01-23 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ielts_service', '0005_questiongroup_container'),
    ]

    operations = [
        migrations.AddField(
            model_name='questiongroup',
            name='group_type',
            field=models.CharField(default='text_input', help_text='Type of questions in this group', max_length=50),
        ),
    ]
