# Generated by Django 6.0 on 2026-01-23 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ielts_service', '0006_questiongroup_group_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='questiongroup',
            name='options',
            field=models.JSONField(blank=True, default=list, help_text='List of options shared by questions in this group'),
        ),
    ]
