# Generated by Django 6.0 on 2026-01-23 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ielts_service', '0007_questiongroup_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='questiongroup',
            name='image',
            field=models.ImageField(blank=True, help_text='Image for diagram/flowchart questions', null=True, upload_to='ielts/images/'),
        ),
    ]
