# Generated by Django 6.0 on 2026-01-27 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ielts_service', '0008_questiongroup_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='supportticket',
            name='is_read',
            field=models.BooleanField(default=False, help_text='True if admin has read the new ticket'),
        ),
        migrations.AddField(
            model_name='ticketreply',
            name='is_read',
            field=models.BooleanField(default=False, help_text='True if the recipient has read this reply'),
        ),
    ]
