"""
Tenant serializers for white-label multi-tenant API.
"""
from rest_framework import serializers
from crm_app.models import Tenant, TenantSettings


class TenantBrandingSerializer(serializers.Serializer):
    """
    Public-facing branding data (no auth required).
    Used by frontend to fetch logo, colors, company name.
    """
    tenant_id = serializers.UUIDField(source='tenant.id', read_only=True)
    name = serializers.CharField(source='tenant.name')
    slug = serializers.CharField(source='tenant.slug')
    company_name = serializers.CharField()
    
    # Dynamic logo/favicon URLs (checks file upload first, then external URL)
    logo = serializers.SerializerMethodField()
    favicon = serializers.SerializerMethodField()
    
    # Brand colors and typography
    primary_color = serializers.CharField()
    secondary_color = serializers.CharField()
    accent_color = serializers.CharField()
    font_family = serializers.CharField()
    
    # Contact info
    support_email = serializers.EmailField(allow_null=True)
    website_url = serializers.URLField(allow_null=True)
    
    def get_logo(self, obj):
        """Return uploaded logo URL if available, otherwise external logo_url"""
        request = self.context.get('request')
        if obj.logo and hasattr(obj.logo, 'url'):
            if request:
                return request.build_absolute_uri(obj.logo.url)
            return obj.logo.url
        return obj.logo_url
    
    def get_favicon(self, obj):
        """Return uploaded favicon URL if available, otherwise external favicon_url"""
        request = self.context.get('request')
        if obj.favicon and hasattr(obj.favicon, 'url'):
            if request:
                return request.build_absolute_uri(obj.favicon.url)
            return obj.favicon.url
        return obj.favicon_url


class TenantSettingsSerializer(serializers.ModelSerializer):
    """
    Full tenant settings for admin management.
    Supports file uploads for logo and favicon.
    """
    tenant_name = serializers.CharField(source='tenant.name', read_only=True)
    tenant_slug = serializers.CharField(source='tenant.slug', read_only=True)
    
    # ImageField URLs (auto-generated by DRF)
    logo = serializers.ImageField(required=False, allow_null=True)
    favicon = serializers.ImageField(required=False, allow_null=True)
    
    class Meta:
        model = TenantSettings
        fields = [
            'tenant_name', 'tenant_slug', 'company_name',
            'logo', 'favicon', 'logo_url', 'favicon_url',
            'primary_color', 'secondary_color', 'accent_color', 'font_family',
            'custom_domain', 'features',
            'support_email', 'website_url',
            'smartflo_api_key', 'smartflo_voicebot_api_key', 'smartflo_caller_id', 'smartflo_config',
            'elevenlabs_api_key', 'elevenlabs_agent_id', 'elevenlabs_config',
            'created_at', 'updated_at'
        ]
        read_only_fields = ['tenant_name', 'tenant_slug', 'created_at', 'updated_at']


class TenantSerializer(serializers.ModelSerializer):
    """
    Core tenant model serializer.
    """
    settings = TenantSettingsSerializer(read_only=True)
    member_count = serializers.SerializerMethodField()
    
    class Meta:
        model = Tenant
        fields = ['id', 'name', 'slug', 'is_active', 'settings', 'member_count', 'created_at', 'updated_at']
        read_only_fields = ['id', 'created_at', 'updated_at']
    
    def get_member_count(self, obj):
        return obj.members.count() if hasattr(obj, 'members') else 0
