# Generated by Django 5.2.8 on 2025-12-05 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0004_auditlog_applicant'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='applicant',
            name='preferred_country',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
