# Generated by Django 5.2.8 on 2025-12-05 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0006_alter_followup_channel'),
    ]

    operations = [
        migrations.AddField(
            model_name='academicrecord',
            name='end_year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='academicrecord',
            name='start_year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
