# Generated by Django 5.2.8 on 2025-12-13 07:49

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0009_adintegration_adcampaign'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Organization/Company name', max_length=255)),
                ('slug', models.SlugField(help_text='URL-safe identifier for the tenant', max_length=100, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Tenant',
                'verbose_name_plural': 'Tenants',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='userprofile',
            name='is_tenant_admin',
            field=models.BooleanField(default=False, help_text='Can manage tenant settings and branding'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='tenant',
            field=models.ForeignKey(blank=True, help_text='The tenant/organization this user belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='members', to='crm_app.tenant'),
        ),
        migrations.CreateModel(
            name='TenantSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(help_text='Display name for the organization', max_length=255)),
                ('logo_url', models.URLField(blank=True, help_text="URL to the tenant's logo", null=True)),
                ('favicon_url', models.URLField(blank=True, help_text="URL to the tenant's favicon", null=True)),
                ('primary_color', models.CharField(default='#6366f1', help_text='Primary brand color (hex)', max_length=7)),
                ('secondary_color', models.CharField(default='#4f46e5', help_text='Secondary brand color (hex)', max_length=7)),
                ('accent_color', models.CharField(default='#8b5cf6', help_text='Accent color (hex)', max_length=7)),
                ('custom_domain', models.CharField(blank=True, help_text='Custom domain for white-label access (e.g., crm.clientcompany.com)', max_length=255, null=True, unique=True)),
                ('features', models.JSONField(blank=True, default=dict, help_text="Feature flags: {'ielts_module': true, 'ai_calls': true, ...}")),
                ('support_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('website_url', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='crm_app.tenant')),
            ],
            options={
                'verbose_name': 'Tenant Settings',
                'verbose_name_plural': 'Tenant Settings',
            },
        ),
    ]
