# Generated by Django 5.2.8 on 2025-12-13 09:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0010_add_tenant_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='tenant',
            field=models.ForeignKey(blank=True, help_text='Tenant this applicant belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='applicants', to='crm_app.tenant'),
        ),
        migrations.AddField(
            model_name='application',
            name='tenant',
            field=models.ForeignKey(blank=True, help_text='Tenant this application belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='crm_app.tenant'),
        ),
        migrations.AddField(
            model_name='callrecord',
            name='tenant',
            field=models.ForeignKey(blank=True, help_text='Tenant this call record belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='call_records', to='crm_app.tenant'),
        ),
        migrations.AddField(
            model_name='followup',
            name='tenant',
            field=models.ForeignKey(blank=True, help_text='Tenant this follow-up belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='followups', to='crm_app.tenant'),
        ),
        migrations.AddField(
            model_name='lead',
            name='tenant',
            field=models.ForeignKey(blank=True, help_text='Tenant this lead belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='leads', to='crm_app.tenant'),
        ),
        migrations.AddField(
            model_name='notification',
            name='tenant',
            field=models.ForeignKey(blank=True, help_text='Tenant this notification belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='crm_app.tenant'),
        ),
    ]
