# Generated by Django 5.2.8 on 2025-12-20 10:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0012_add_document_upload_token'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='outboundmessage',
            options={'ordering': ('-created_at',), 'verbose_name': 'Message', 'verbose_name_plural': 'Messages'},
        ),
        migrations.AddField(
            model_name='outboundmessage',
            name='applicant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages', to='crm_app.applicant'),
        ),
        migrations.AddField(
            model_name='outboundmessage',
            name='channel',
            field=models.CharField(choices=[('whatsapp', 'WhatsApp'), ('sms', 'SMS')], default='whatsapp', max_length=16),
        ),
        migrations.AddField(
            model_name='outboundmessage',
            name='delivered_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='outboundmessage',
            name='direction',
            field=models.CharField(choices=[('outbound', 'Outbound'), ('inbound', 'Inbound')], default='outbound', max_length=16),
        ),
        migrations.AddField(
            model_name='outboundmessage',
            name='error_message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='outboundmessage',
            name='is_from_ai',
            field=models.BooleanField(default=False, help_text='Whether this message was generated by AI'),
        ),
        migrations.AddField(
            model_name='outboundmessage',
            name='lead',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages', to='crm_app.lead'),
        ),
        migrations.AddField(
            model_name='outboundmessage',
            name='read_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='outboundmessage',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='crm_app.tenant'),
        ),
        migrations.AlterField(
            model_name='outboundmessage',
            name='status',
            field=models.CharField(choices=[('queued', 'Queued'), ('sent', 'Sent'), ('delivered', 'Delivered'), ('read', 'Read'), ('failed', 'Failed')], default='queued', max_length=32),
        ),
    ]
