# Generated by Django 5.2.8 on 2025-12-23 07:25

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0013_extend_outbound_message'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Template name for identification', max_length=100)),
                ('trigger', models.CharField(choices=[('post_call', 'After Call Ends'), ('document_reminder', 'Document Reminder'), ('welcome', 'Welcome Message'), ('follow_up', 'Follow-up Message'), ('custom', 'Custom Trigger')], default='post_call', max_length=50)),
                ('channel', models.CharField(choices=[('whatsapp', 'WhatsApp'), ('sms', 'SMS'), ('both', 'WhatsApp & SMS')], default='whatsapp', max_length=20)),
                ('content', models.TextField(help_text='Message content. Variables: {name}, {first_name}, {application_id}, {phone}, {upload_link}, {call_date}')),
                ('is_active', models.BooleanField(default=True)),
                ('is_default', models.BooleanField(default=False, help_text='Default template for this trigger')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(blank=True, help_text='Tenant this template belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='message_templates', to='crm_app.tenant')),
            ],
            options={
                'verbose_name': 'Message Template',
                'verbose_name_plural': 'Message Templates',
                'ordering': ('-is_default', '-updated_at'),
            },
        ),
    ]
