# Generated by Django 5.2.8 on 2025-12-24 11:03

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0014_messagetemplate'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='accommodation_arranged',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='application',
            name='conditions',
            field=models.TextField(blank=True, help_text='Offer conditions to be met', null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='deposit_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='deposit_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='application',
            name='deposit_paid_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='enrollment_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='fee_currency',
            field=models.CharField(default='USD', max_length=8),
        ),
        migrations.AddField(
            model_name='application',
            name='flight_booked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='application',
            name='full_fee_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='application',
            name='i20_cas_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='i20_cas_received_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='i20_cas_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='intake',
            field=models.CharField(blank=True, choices=[('fall_2024', 'Fall 2024'), ('spring_2025', 'Spring 2025'), ('fall_2025', 'Fall 2025'), ('spring_2026', 'Spring 2026'), ('fall_2026', 'Fall 2026')], max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='offer_deadline',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='offer_letter_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='offer_received_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='offer_type',
            field=models.CharField(blank=True, choices=[('conditional', 'Conditional Offer'), ('unconditional', 'Unconditional Offer')], max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='planned_departure_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='priority',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=16),
        ),
        migrations.AddField(
            model_name='application',
            name='program_type',
            field=models.CharField(blank=True, choices=[('bachelors', "Bachelor's Degree"), ('masters', "Master's Degree"), ('phd', 'PhD/Doctorate'), ('diploma', 'Diploma'), ('certificate', 'Certificate'), ('language', 'Language Course')], max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='sevis_id',
            field=models.CharField(blank=True, help_text='SEVIS ID for F-1 visas', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='stage',
            field=models.CharField(choices=[('inquiry', 'Inquiry'), ('documents_pending', 'Documents Pending'), ('application_submitted', 'Application Submitted'), ('offer_received', 'Offer Received'), ('fee_paid', 'Fee Paid'), ('i20_cas_received', 'I-20/CAS Received'), ('visa_applied', 'Visa Applied'), ('visa_interview', 'Visa Interview'), ('visa_approved', 'Visa Approved'), ('pre_departure', 'Pre-Departure'), ('enrolled', 'Enrolled'), ('rejected', 'Rejected'), ('withdrawn', 'Withdrawn')], default='inquiry', max_length=32),
        ),
        migrations.AddField(
            model_name='application',
            name='stage_history',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='application',
            name='tuition_fee',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='university_application_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='visa_application_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='visa_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='application',
            name='visa_decision_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='visa_expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='visa_interview_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='visa_interview_location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='visa_rejection_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='visa_type',
            field=models.CharField(blank=True, choices=[('f1', 'F-1 (USA)'), ('j1', 'J-1 (USA)'), ('tier4', 'Tier 4 (UK)'), ('student_visa', 'Student Visa'), ('study_permit', 'Study Permit (Canada)'), ('subclass_500', 'Subclass 500 (Australia)'), ('other', 'Other')], max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_applications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='application',
            name='program',
            field=models.CharField(blank=True, help_text='Program/Course name', max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='ApplicationDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('passport', 'Passport'), ('transcript', 'Academic Transcript'), ('degree_certificate', 'Degree Certificate'), ('sop', 'Statement of Purpose'), ('lor', 'Letter of Recommendation'), ('resume', 'Resume/CV'), ('financial_proof', 'Financial Documents'), ('english_test', 'English Test Score (IELTS/TOEFL)'), ('gre_gmat', 'GRE/GMAT Score'), ('offer_letter', 'Offer Letter'), ('i20_cas', 'I-20/CAS Document'), ('visa_application', 'Visa Application Form'), ('visa_photo', 'Visa Photo'), ('medical_report', 'Medical Report'), ('police_clearance', 'Police Clearance'), ('travel_itinerary', 'Travel Itinerary'), ('insurance', 'Insurance Documents'), ('other', 'Other')], max_length=32)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('file_url', models.URLField(blank=True, null=True)),
                ('file_name', models.CharField(blank=True, max_length=255, null=True)),
                ('file_size', models.IntegerField(blank=True, help_text='File size in bytes', null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending Upload'), ('uploaded', 'Uploaded'), ('under_review', 'Under Review'), ('verified', 'Verified'), ('rejected', 'Rejected'), ('expired', 'Expired')], default='pending', max_length=32)),
                ('is_required', models.BooleanField(default=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('uploaded_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='crm_app.application')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['document_type', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('short_name', models.CharField(blank=True, max_length=50, null=True)),
                ('country', models.CharField(max_length=100)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('state_province', models.CharField(blank=True, max_length=100, null=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('logo_url', models.URLField(blank=True, null=True)),
                ('ranking', models.IntegerField(blank=True, help_text='University ranking', null=True)),
                ('application_deadline_info', models.TextField(blank=True, null=True)),
                ('tuition_range', models.CharField(blank=True, max_length=100, null=True)),
                ('acceptance_rate', models.FloatField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(blank=True, help_text='Tenant this university belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='universities', to='crm_app.tenant')),
            ],
            options={
                'verbose_name_plural': 'Universities',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='application',
            name='university',
            field=models.ForeignKey(blank=True, help_text='Target university', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applications', to='crm_app.university'),
        ),
    ]
