# Generated by Django 5.2.8 on 2026-01-06 10:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0015_extend_application_visa_workflow'),
    ]

    operations = [
        migrations.CreateModel(
            name='VoiceAgent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Internal name for this agent', max_length=100)),
                ('provider', models.CharField(choices=[('elevenlabs', 'ElevenLabs'), ('retell', 'Retell AI'), ('vapi', 'Vapi')], default='elevenlabs', max_length=20)),
                ('provider_agent_id', models.CharField(help_text='The ID from the provider (e.g., ElevenLabs Agent ID)', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='voice_agents', to='crm_app.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='PhoneNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(help_text='E.164 format e.g. +918069652687', max_length=20, unique=True)),
                ('provider', models.CharField(default='smartflo', help_text='Provider name (e.g. Smartflo)', max_length=50)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='phone_numbers', to='crm_app.tenant')),
                ('inbound_agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='phone_numbers', to='crm_app.voiceagent')),
            ],
        ),
        migrations.CreateModel(
            name='TelephonyConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('smartflo', 'Smartflo'), ('elevenlabs', 'ElevenLabs')], max_length=50)),
                ('api_key_encrypted', models.TextField(blank=True, help_text='Encrypted API Key', null=True)),
                ('api_secret_encrypted', models.TextField(blank=True, help_text='Encrypted API Secret (if applicable)', null=True)),
                ('base_url', models.URLField(blank=True, help_text='Override Base URL if needed', null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='telephony_configs', to='crm_app.tenant')),
            ],
            options={
                'unique_together': {('tenant', 'provider')},
            },
        ),
    ]
