# Generated by Django 5.2.8 on 2026-01-06 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0016_voiceagent_phonenumber_telephonyconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='voiceagent',
            name='config',
            field=models.JSONField(blank=True, default=dict, help_text='Provider specific settings (JSON)'),
        ),
        migrations.AddField(
            model_name='voiceagent',
            name='type',
            field=models.CharField(choices=[('inbound', 'Inbound'), ('outbound', 'Outbound'), ('general', 'General')], default='general', max_length=20),
        ),
    ]
