# Generated by Django 5.2.8 on 2026-01-06 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0017_voiceagent_config_voiceagent_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='database_schema',
            field=models.CharField(blank=True, help_text='Database schema name for tenant isolation (e.g., tenant_acme_corp)', max_length=100, null=True, unique=True),
        ),
    ]
