# Generated by Django 6.0 on 2026-01-09 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0018_add_tenant_database_schema'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telephonyconfig',
            name='provider',
            field=models.CharField(choices=[('smartflo', 'Smartflo'), ('elevenlabs', 'ElevenLabs'), ('openai', 'OpenAI')], max_length=50),
        ),
    ]
