# Generated by Django 5.2.8 on 2026-01-09 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0019_alter_telephonyconfig_provider'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenantsettings',
            name='logo',
            field=models.ImageField(blank=True, help_text='Uploaded logo image', null=True, upload_to='tenant_logos/'),
        ),
        migrations.AlterField(
            model_name='tenantsettings',
            name='logo_url',
            field=models.URLField(blank=True, help_text="URL to the tenant's logo (Legacy/External)", null=True),
        ),
    ]
