# Generated by Django 5.2.8 on 2025-12-19 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ielts_service', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='questiongroup',
            name='audio_start_time',
            field=models.PositiveIntegerField(default=0, help_text='Time in seconds when this section starts in the audio file. Used for auto-switching parts.'),
        ),
    ]
