# Generated by Django 5.2.8 on 2025-12-23 05:31

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ielts_service', '0002_add_audio_start_time'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IELTSStudentProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('google_id', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('target_score', models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True)),
                ('exam_date', models.DateField(blank=True, null=True)),
                ('test_type', models.CharField(blank=True, choices=[('academic', 'Academic'), ('general', 'General')], max_length=20)),
                ('attempt_type', models.CharField(blank=True, max_length=50)),
                ('purpose', models.CharField(blank=True, choices=[('study_abroad', 'Study Abroad'), ('immigration', 'Immigration'), ('work_abroad', 'Work Abroad'), ('local_university', 'Study at Local University'), ('other', 'Other Reasons'), ('teacher', 'IELTS Teacher')], max_length=50)),
                ('referral_source', models.CharField(blank=True, max_length=50)),
                ('onboarding_completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ielts_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
