# Generated by Django 5.2.8 on 2025-12-29 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ielts_service', '0003_ieltsstudentprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='ieltsstudentprofile',
            name='account_type',
            field=models.CharField(choices=[('crm', 'CRM Enrolled Student'), ('self_signup', 'Self-Signup Student')], default='self_signup', max_length=20),
        ),
        migrations.AddField(
            model_name='ieltsstudentprofile',
            name='evaluations_this_week',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ieltsstudentprofile',
            name='last_evaluation_reset',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ieltsstudentprofile',
            name='subscription_status',
            field=models.CharField(choices=[('free', 'Free Tier'), ('premium', 'Premium Subscription'), ('crm_full', 'CRM Full Access')], default='free', max_length=20),
        ),
        migrations.AddField(
            model_name='ieltsstudentprofile',
            name='weekly_evaluation_limit',
            field=models.PositiveIntegerField(default=3),
        ),
    ]
