# Generated by Django 5.2.8 on 2025-12-30 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ielts_service', '0004_ieltsstudentprofile_account_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='questiongroup',
            name='container',
            field=models.JSONField(blank=True, default=dict, help_text='Rich text container with slots for inline answers'),
        ),
        migrations.AddField(
            model_name='questiongroup',
            name='group_type',
            field=models.CharField(choices=[('standard', 'Standard Questions'), ('summary_completion', 'Summary Completion'), ('table_completion', 'Table Completion'), ('matching_features', 'Matching Features'), ('matching_headings', 'Matching Headings'), ('true_false_ng', 'True/False/Not Given'), ('yes_no_ng', 'Yes/No/Not Given'), ('multiple_choice', 'Multiple Choice'), ('sentence_completion', 'Sentence Completion')], default='standard', max_length=30),
        ),
        migrations.AddField(
            model_name='questiongroup',
            name='options',
            field=models.JSONField(blank=True, default=list, help_text='List of options/word bank for this question group'),
        ),
    ]
