# Generated by Django 5.2.8 on 2025-12-30 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ielts_service', '0005_add_question_group_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='questiongroup',
            name='image',
            field=models.CharField(blank=True, help_text='URL to an image for diagram/flowchart questions', max_length=500),
        ),
    ]
