# Generated by Django 5.2.8 on 2025-12-31 05:31

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ielts_service', '0006_questiongroup_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SpeakingResponse',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('part', models.PositiveSmallIntegerField()),
                ('question_index', models.PositiveSmallIntegerField(default=0)),
                ('question_text', models.TextField()),
                ('audio_file', models.FileField(blank=True, null=True, upload_to='speaking_audio/%Y/%m/%d/')),
                ('audio_duration_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('transcript', models.TextField(blank=True)),
                ('word_count', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('listening', 'Listening'), ('processing', 'Processing'), ('analyzing', 'Analyzing'), ('completed', 'Completed'), ('failed', 'Failed'), ('skipped', 'Skipped')], default='pending', max_length=20)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('end_reason', models.CharField(blank=True, help_text='Why speaking ended: silence_threshold, time_limit, manual_stop', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Speaking Response',
                'verbose_name_plural': 'Speaking Responses',
                'ordering': ['session', 'part', 'question_index'],
            },
        ),
        migrations.CreateModel(
            name='SpeakingMetrics',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('total_speaking_time_ms', models.PositiveIntegerField(default=0)),
                ('total_silence_time_ms', models.PositiveIntegerField(default=0)),
                ('total_duration_ms', models.PositiveIntegerField(default=0)),
                ('pause_count', models.PositiveIntegerField(default=0)),
                ('avg_pause_duration_ms', models.PositiveIntegerField(default=0)),
                ('max_pause_duration_ms', models.PositiveIntegerField(default=0)),
                ('long_pause_count', models.PositiveIntegerField(default=0, help_text='Pauses > 2 seconds')),
                ('estimated_words_per_minute', models.PositiveIntegerField(default=0)),
                ('syllables_per_minute', models.PositiveIntegerField(default=0)),
                ('speech_ratio', models.FloatField(default=0.0, help_text='Ratio of speaking time to total time')),
                ('fluency_score', models.FloatField(default=0.0, help_text='Computed fluency based on pauses and continuity')),
                ('continuity_score', models.FloatField(default=0.0, help_text='How continuous the speech was (fewer interruptions = higher)')),
                ('avg_amplitude', models.FloatField(default=0.0)),
                ('amplitude_variance', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('response', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='ielts_service.speakingresponse')),
            ],
            options={
                'verbose_name': 'Speaking Metrics',
                'verbose_name_plural': 'Speaking Metrics',
            },
        ),
        migrations.CreateModel(
            name='SpeakingEvaluation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fluency_coherence', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('fluency_coherence_feedback', models.TextField(blank=True)),
                ('lexical_resource', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('lexical_resource_feedback', models.TextField(blank=True)),
                ('grammatical_range', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('grammatical_range_feedback', models.TextField(blank=True)),
                ('pronunciation', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('pronunciation_feedback', models.TextField(blank=True)),
                ('overall_band', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('improvement_suggestions', models.TextField(blank=True)),
                ('strengths', models.TextField(blank=True)),
                ('weaknesses', models.TextField(blank=True)),
                ('raw_evaluation_response', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('response', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='evaluation', to='ielts_service.speakingresponse')),
            ],
            options={
                'verbose_name': 'Speaking Evaluation',
                'verbose_name_plural': 'Speaking Evaluations',
            },
        ),
        migrations.CreateModel(
            name='SpeakingSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('initializing', 'Initializing'), ('active', 'Active'), ('analyzing', 'Analyzing'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='initializing', max_length=20)),
                ('current_part', models.PositiveSmallIntegerField(default=1)),
                ('current_question_index', models.PositiveSmallIntegerField(default=0)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('overall_band_score', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('fluency_coherence_avg', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('lexical_resource_avg', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('grammatical_range_avg', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('pronunciation_avg', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('test', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='speaking_sessions', to='ielts_service.ieltstest')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='speaking_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Speaking Session',
                'verbose_name_plural': 'Speaking Sessions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='speakingresponse',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='ielts_service.speakingsession'),
        ),
        migrations.AlterUniqueTogether(
            name='speakingresponse',
            unique_together={('session', 'part', 'question_index')},
        ),
    ]
