# Generated by Django 5.2.8 on 2026-01-06 07:16

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ielts_service', '0007_speaking_test_models'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SpeakingRecording',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('test_id', models.CharField(help_text='Speaking test ID', max_length=50)),
                ('session_id', models.CharField(blank=True, help_text='Unique session identifier', max_length=100)),
                ('label', models.CharField(help_text='Part 1 - Q1, Part 2, etc.', max_length=100)),
                ('audio_file', models.FileField(upload_to='ielts/speaking_recordings/')),
                ('duration_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('transcript', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='speaking_recordings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
